import React, { useState } from 'react';
import Button from '../../components/Button';

export default function SensualServices() {
    const [first, setFirst] = useState(false);
    const [second, setSecond] = useState(false);
    const [third, setThird] = useState(false);
    const [fourth, setFourth] = useState(false);
    const [fifth, setFifth] = useState(false);
    const [six, setSix] = useState(false);
    const [seven, setSeven] = useState(false);
    const [eight, setEight] = useState(false);
    const [nine, setNine] = useState(false);
    const [ten, setTen] = useState(false);
    const [eleven, setEleven] = useState(false);
    const [twelve, setTwelve] = useState(false);
    const [thirteen, setThirteen] = useState(false);
    const [fourteen, setFourteen] = useState(false);
    const [fifteen, setFifteen] = useState(false);
    const [sixteen, setSixteen] = useState(false);
    const [seventeen, setSeventeen] = useState(false);
    const [eighteen, setEighteen] = useState(false);
    const [nineteen, setNineteen] = useState(false);
    const [twenty, setTwenty] = useState(false);
    const [twentyOne, setTwentyOne] = useState(false);
    const [twentyTwo, setTwentyTwo] = useState(false);
    const [twentyThree, setTwentyThree] = useState(false);
    const [twentyFour, setTwentyFour] = useState(false);
    const [twentyFive, setTwentyFive] = useState(false);
    const [twentySix, setTwentySix] = useState(false);
    const [twentySeven, setTwentySeven] = useState(false);
    const [twentyEight, setTwentyEight] = useState(false);
    const [twentyNine, setTwentyNine] = useState(false);
    const [thirty, setThirty] = useState(false);
    const [thirtyOne, setThirtyOne] = useState(false);
    const [thirtyTwo, setThirtyTwo] = useState(false);
    const [thirtyThree, setThirtyThree] = useState(false);
    const [thirtyFour, setThirtyFour] = useState(false);
    const [thirtyFive, setThirtyFive] = useState(false);
    const [thirtySix, setThirtySix] = useState(false);
    const [thirtySeven, setThirtySeven] = useState(false);
    const [thirtyEight, setThirtyEight] = useState(false);
    return (
        <div className='main-container'>
            <div className='w-full mx-auto flex flex-col justify-center items-center pt-4'>
                <div className='w-full mx-auto flex items-center justify-center'><span className='font-bold text-[26px]'>Sensual Services</span></div>
                <div className='w-[100vw] flex items-center justify-center bg-gradient-to-b from-[#02227E] to-[#0247FF] mt-4'><span className='font-bold text-[24px] text-white'>Set Up</span></div>
                <div className='w-full mx-auto flex items-center justify-center mt-2'><span className='font-bold text-[16px] text-[#02227E]'>Please be thorough so the community can find you</span></div>
                <div className='grid grid-cols-2 gap-4 mt-6'>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${first == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFirst(!first)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Girlfriend Experience</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${second == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSecond(!second)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>PornStar Experience</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${third == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThird(!third)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>French Kissing</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fourth == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFourth(!fourth)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Cunnilingus</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fifth == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFifth(!fifth)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>BBBJ</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${six == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSix(!six)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>CBJ</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${seven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSeven(!seven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Deepthroat</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eight == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEight(!eight)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Cum in mouth</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${nine == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setNine(!nine)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Msog</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${ten == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTen(!ten)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Swallowing</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eleven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEleven(!eleven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Prostate play</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twelve == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwelve(!twelve)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Anal</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirteen(!thirteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Rimming</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fourteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFourteen(!fourteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Fingering</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fifteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFifteen(!fifteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>4 handed</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${sixteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSixteen(!sixteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Pegging</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${seventeen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSeventeen(!seventeen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Kamasutra</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eighteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEighteen(!eighteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Erotic massage</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${nineteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setNineteen(!nineteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Duo with girl</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twenty == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwenty(!twenty)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Couples</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyOne == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyOne(!twentyOne)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Group sex</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyTwo == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyTwo(!twentyTwo)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>With 2 men</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyThree == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyThree(!twentyThree)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Hand Job</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyFour == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyFour(!twentyFour)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Foot Job</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyFive == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyFive(!twentyFive)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Bdsm</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentySix == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentySix(!twentySix)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Foot fetish</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentySeven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentySeven(!twentySeven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Submissive</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyEight == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyEight(!twentyEight)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Femdom</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyNine == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyNine(!twentyNine)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Dirty Talk</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirty == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirty(!thirty)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Masturbation</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyOne == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyOne(!thirtyOne)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>69 position</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyTwo == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyTwo(!thirtyTwo)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Cum in face</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyThree == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyThree(!thirtyThree)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Casual photos</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyFour == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyFour(!thirtyFour)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Cum on body</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyFive == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyFive(!thirtyFive)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Golden shower</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtySix == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtySix(!thirtySix)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Video with sex</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtySeven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtySeven(!thirtySeven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Virtual Sessions</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirtyEight == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirtyEight(!thirtyEight)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Only Fans</span></div></div>
                </div>
                <div className='w-full mx-auto flex flex-row justify-between items-center mt-6'>
                    <div className='w-[160px]'><Button className={'flex items-center justify-center border-2 border-[#02227E] rounded-[15px] bg-[#05B7FD] font-bold text-[16px] text-[#02227E]'} text="Massage Services Setup>>" /></div>
                    <div className='w-[160px]'><Button className={'flex items-center justify-center border-2 border-[#02227E] rounded-[15px] bg-[#05B7FD] font-bold text-[16px] text-[#02227E]'} text="Erotic Dance Setup>>" /></div>
                </div>
                <div className='w-full mx-auto flex items-center justify-center mt-6'>
                    <div className='w-[97px]'><Button text="Next>>" className={'flex items-center justify-center border-2 border-[#02227E] rounded-[10px] bg-[#05B7FD] font-bold text-[18px] text-[#02227E] h-[36px]'} size="36px" /></div>
                </div>
            </div>
        </div>
    );
}