import React from "react";
import Sidebarnav from "../Components/Sidebarnav";

const Privacypolicy = () => {
  return (
    <div>
      <div>
        <div className="max-w-[820px] mx-auto">
          <Sidebarnav />
          <div className="bg-white pb-2 h-[80%] w-full rounded-[50px] mt-5 ">
            <div className="w-[90%] mx-auto items-center mt-16 py-5">
              <h1 className="text-[20px] text-[#0247FF] font-bold text-center">
                PRIVACY POLICY
              </h1>
              <h2 className="text-[16px] font-bold pt-5">
                Last updated: May 1st 2023
              </h2>
              <p className="text-[16px] pt-2">
                At Vairify.Date, one of our main priorities is the privacy of
                our visitors/ members. This Privacy Policy document contains
                types of information that are collected and recorded by
                Vairify.Date, how we use it, how we store your data, tenure for
                storing your personal information and advertisement of content
                etc. <br />
                This privacy policy is made in accordance with all the
                International Privacy Standards and laws such as GDPR, CCPR, and
                CalOPPA which ensures the privacy of our users. If you have
                additional questions or require more information about our
                Privacy Policy, do not hesitate to contact us. <br />
                This Privacy Policy applies only to our online activities and is
                valid for visitors to our website with regards to the
                information that they shared and/or collect in Vairify.Date.
              </p>
              <h2 className="text-[16px] font-bold pt-5">Interpretation:</h2>
              <p className="text-[16px] pt-2">
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or plural. For this Privacy Policy:
                Company: (referred to as either the Company; We; Us or Our in
                this Agreement) refers to sexEpros Inc. Country refers to the
                Panama. Device means any device that can access the Service such
                as a computer, a cellphone or a digital tablet. Personal refers
                to any information that relates to an identified or identifiable
                individual. Service refers to the Website. Service Provider
                means any natural or legal person who processes the data on
                behalf of the Company. It refers to third-party companies or
                individuals employed by the Company to facilitate the Service,
                to provide the Service on behalf of the Company, to perform
                services related to the Service or to assist the Company in
                analyzing how the Service is used. Third-party Social Media
                Service refers to any website or any social network website
                through which a user can log in or create an account to use the
                Service. Usage Data refers to data collected automatically,
                either generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit). Website refers Vairify.Date. You mean the individual
                accessing or using the Service, or the company, or other legal
                entity on behalf of which such individual is accessing or using
                the Service, as applicable. <br />
                Consent: <br />
                By using our website, you hereby consent to our Privacy Policy
                and agree to its terms.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Information We Collect:
              </h2>
              <p className="text-[16px] pt-2">
                We collect your driver’s license information solely for the
                purpose of verifying your identity through a third-party KYC
                process called Know Your Client. This process involves an AI
                validation and a selfie to confirm that you are the legitimate
                holder of the state ID. Once verified, we replace your personal
                information with a site-generated number that is used for the
                Verified Anonymous Identity (VAI) process on our site. We do not
                retain your personal information but may retrieve it if required
                by law. Our company is registered in Panama, and we maintain
                control over the release of information to government agencies,
                including those in the United States. For example, we would
                disclose your personal information to the authorities in case of
                a criminal investigation, such as murder. However, we would not
                comply with requests for identity information in cases of
                infidelity or tax evasion, as we are committed to maintaining
                anonymity and trust with our users.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                The Accuracy and Retention of Personal Information:
              </h2>
              <p className="text-[16px] pt-2">
                We endeavor to ensure that any Personal Information in our
                possession is as accurate, current and complete as necessary for
                the purposes for which we use and/or disclose such Personal
                Information. If we become aware that your Personal Information
                in our possession is inaccurate, out-of-date or incomplete, we
                will endeavor to revise such Personal Information accordingly.
                We will retain your Personal Information only for so long as it
                is required for the purposes it was collected or as required by
                applicable laws, regulations, or government orders. This period
                may extend beyond the end of your relationship with us, but it
                will be only for so long as it is reasonably necessary for us to
                have sufficient information to respond to any issues that may
                arise after the end of your relationship with us. When your
                Personal Information is no longer required, we will destroy or
                delete it.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Protection of Personal Information:
              </h2>
              <p className="text-[16px] pt-2">
                We endeavor to maintain appropriate physical, procedural and
                technical safeguards with respect to our offices and information
                storage facilities in order to prevent any loss, misuse, or un
                authorized access, disclosure, or modification of Personal
                Information. However, no method of transmission over the
                Internet, or method of electronic storage, is 100% secure. We
                cannot ensure or warrant the security of any information you
                transmit to us and you do so at your own risk. We also cannot
                guarantee that such information may not be accessed, disclosed,
                altered, or destroyed by breach of any of our physical,
                procedural, or technical safeguards. If you believe your
                Personal Information has been compromised, please contact us as
                set forth in the “Contact Us” section. If we learn of a security
                systems breach, we will inform you and the authorities of the
                occurrence of the breach in accordance with applicable law.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                How Do We Collect Your Data?
              </h2>
              <p className="text-[16px] pt-2">
                We collect date directly from the users.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                How We Use Your Information?
              </h2>
              <p className="text-[16px] pt-2">
                We use the information we collect in various ways, including:{" "}
                <br />
                • Provide, operate, and maintain our website <br />
                • Improve, personalize, and expand our website <br />
                • Understand and analyze how you use our website <br />• Develop
                new products, services, features, and functionality <br />•
                Process your order, with internal advertising
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                How Do We Store Your Data?
              </h2>
              <p className="text-[16px] pt-2">
                To maintain anonymity and accountability for all actions, we
                store all data and information under your site-generated ID.
                This means that your personal information is not associated with
                your identity but is stored securely under your unique
                identifier. We take all necessary measures to ensure that your
                data is protected from unauthorized access, modification, or
                disclosure. Our data storage systems are regularly monitored,
                and we follow industry-standard security practices to ensure the
                confidentiality, integrity, and availability of your data. If
                you have any concerns or questions about our data storage
                practices, please do not hesitate to contact us.
              </p>
              <h2 className="text-[16px] font-bold pt-5">Log Files:</h2>
              <p className="text-[16px] pt-2">
                Vairify.Date follows a standard procedure of using log files.
                These files log visitors when they visit websites. All hosting
                companies do this and a part of hosting services' analytics. The
                information collected by log files includes internet protocol
                (IP) addresses, browser type, Internet Service Provider (ISP),
                date and time stamp, referring/exit pages, and possibly the
                number of clicks. These are not linked to any personally
                identifiable information. The purpose of the information is for
                analyzing trends, administering the site, tracking users'
                movement on the website, and gathering demographic information.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Use of Google Analytics And Other Tools:{" "}
              </h2>
              <p className="text-[16px] pt-2">
                We use Google Analytics or other tools for our services
                (Website) in order to provide our customers with a high quality
                services. These tools also provide us with all the necessary
                information about the Website statistics, e.g. who visits our
                Website, number of visitors to our Website, where they come
                from, which device they use. It also helps us measure the
                performance of our Website, optimize web pages to increase
                conversion, divide users into different segments like age,
                gender, country, device, etc. and understand what type of
                content should be created.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Advertising Partners:
              </h2>
              <p className="text-[16px] pt-2">
                Our Company would like to send you information about products
                and services of ours that we think you might like, as well as
                those of our partner companies. Every of our partner companies
                has its own privacy rules and we will not responsible for them.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                CCPA Privacy Rights (Do Not Sell My Personal Information):
              </h2>
              <p className="text-[16px] pt-2">
                Under the CCPA, among other rights, California consumers have
                the right to: <br />
                • Request that a business that collects a consumer's data
                disclose the categories and specific pieces of personal data
                that a business has collected about consumers. <br />
                • Request that a business deletes any personal data about the
                consumer that a business has collected. <br />
                • Request that a business that sells a consumer's data, not sell
                the consumer's data. <br />
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                GDPR Data Protection Rights:
              </h2>
              <p className="text-[16px] pt-2">
                We would like to make sure you are fully aware of all of your
                data protection rights. Every user is entitled to the following:{" "}
                <br />
                The right to access – You have the right to request copies of
                your data. We may charge you a small fee for this service.{" "}
                <br />
                The right to rectification – You have the right to request that
                we correct any information you believe is inaccurate. You also
                have the right to request that we complete the information you
                believe is incomplete. <br />
                The right to erasure – You have the right to request that we
                erase your data, under certain conditions. <br />
                The right to restrict processing – You have the right to request
                that we restrict the processing of your data, under certain
                conditions. <br />
                The right to object to processing – You have the right to object
                to our processing of your data, under certain conditions. <br />
                The right to data portability – You have the right to request
                that we transfer the data that we have collected to another
                organization, or directly to you, under certain conditions.{" "}
                <br />
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                CalOPPA (California Online Privacy Protection Act):
              </h2>
              <p className="text-[16px] pt-2">
                Although it does apply to California-based businesses as well,
                CalOPPA pertains to any company that collects personal
                information from California residents regardless of where that
                company is located. Because of the global nature of the
                internet, this law not only applies to most any business in the
                USA but it can also be (and has been) enforced in other
                countries as well. In our case, as we have traffic from all over
                the world so our privacy policy complies with the CalOPPA as
                well. Note: CalOPPA requires that all information you collect
                about Visitors be listed within your Privacy Policy. This
                includes both the information you collect directly from users,
                data that is collected automatically such as IP address, and
                data you collect from visitor such as email etc. We provide all
                such information in our privacy policy so we fulfil the criteria
                of CalOPPA requirement.{" "}
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Changes To This Privacy Policy:
              </h2>
              <p className="text-[16px] pt-2">
                We may update Our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page. We will let you know via email and/or a prominent
                notice on Our Service, before the change becoming effective and
                update; last updated; date at the top of this Privacy Policy.
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
              <h2 className="text-[16px] font-bold pt-5">
                Children's Information:
              </h2>
              <p className="text-[16px] pt-2">
                Another part of our priority is adding protection for children
                while using the internet. We encourage parents and guardians to
                observe, participate in, and/or monitor and guide their online
                activity. <br />
                Vairify.Date does not knowingly collect any Personal
                Identifiable Information from children under the age of 13. If
                you think that your child provided this kind of information on
                our website, we strongly encourage you to contact us immediately
                and we will do our best efforts to promptly remove such
                information from our records.
              </p>
              <h2 className="text-[16px] font-bold pt-5">Contact Us:</h2>
              <p className="text-[16px] pt-2">
                For more information, contact us by visiting our website
                Vairify.Date or; Via Email: ____________
              </p>
            </div>
          </div>
          <div className="w-[90%] mx-auto pt-6 pb-4">
            <img src="images/Group.svg" alt />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacypolicy;
