import React from 'react';
import Button from '../../components/Button';

export default function DateGuardInvitedMembers() {
    return (
        <div className='main-container'>
            <div className='w-full mx-auto flex flex-col justify-center items-center pt-2'>
                <div className='w-full mx-auto flex items-center justify-center'><span className='font-bold text-[30px] text-[#05B7FD]'>Date Guard</span></div>
                <div className='w-full mx-auto flex items-center justify-center mt-4'><div className='w-[67px] h-[82px]'><img src={process.env.PUBLIC_URL + '/images/DateGuardMask.png'} alt="Date Guard Mask" /></div></div>
                <div className='w-full mx-auto flex items-center justify-center mt-6'><span className='font-bold text-[30px] text-white'>Atlanta</span></div>
                <div className='w-full mx-auto flex flex-col justify-center items-center mt-4'>
                    <div className='relative mt-5'><div style={{left: '2px'}} className='absolute w-[44px] z-20'><Button text="+" className='font-bold text-[35px] rounded-[50%] bg-[#05B7FD] h-[44px] flex items-center justify-center pb-2' size="44px" /></div><div className='relative w-[245px] h-[45px] bg-[#4200FF] rounded-[25px] border-2 border-[#4200FF]'><span style={{left: '20px'}} className='font-bold text-[24px] text-white relative'>Add/Members</span></div></div>
                </div>
                <div className='w-full mx-auto flex flex-row justify-center items-center mt-4'>
                    <div className='mr-6 flex flex-row justify-center items-center'><div className='mr-2 w-[18px] h-[16px] bg-[#05B7FD] border-2 border-white'></div><div><span className='font-bold text-[18px] text-white'>Invited</span></div></div>
                    <div className='flex flex-row justify-center items-center'><div className='mr-2 w-[18px] h-[16px] bg-[#4200FF] border-2 border-white'></div><div><span className='font-bold text-[18px] text-white'>Invited</span></div></div>
                </div>
                <div className='w-full mx-auto flex flex-col justify-start items-center mt-8 mb-4 max-h-[190px] overflow-scroll'>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Julian Brown</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>halley smith</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#4040E1]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Robert Geff</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Jeff Blank</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Avery Jabber</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Julian Brown</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>halley smith</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#4040E1]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Robert Geff</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Jeff Blank</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                    <div className='w-[260px] flex flex-row justify-between items-center flex-wrap mt-4'><div className='w-[25px] h-[25px] rounded-[50%] flex items-center justify-center bg-[#05B7FD]'><img src={process.env.PUBLIC_URL + '/images/Check.png'} alt="Check Icon" /></div><div className=''><span className='font-bold text-[16px] text-white'>Avery Jabber</span></div><div><span className='font-bold text-[16px] text-white'>+12124567890</span></div></div>
                </div>
            </div>
        </div>
    )
}