import React, { useState } from 'react';
import Button from '../../components/Button';

export default function MassageServicesSetUp() {
    const [first, setFirst] = useState(false);
    const [second, setSecond] = useState(false);
    const [third, setThird] = useState(false);
    const [fourth, setFourth] = useState(false);
    const [fifth, setFifth] = useState(false);
    const [six, setSix] = useState(false);
    const [seven, setSeven] = useState(false);
    const [eight, setEight] = useState(false);
    const [nine, setNine] = useState(false);
    const [ten, setTen] = useState(false);
    const [eleven, setEleven] = useState(false);
    const [twelve, setTwelve] = useState(false);
    const [thirteen, setThirteen] = useState(false);
    const [fourteen, setFourteen] = useState(false);
    const [fifteen, setFifteen] = useState(false);
    const [sixteen, setSixteen] = useState(false);
    const [seventeen, setSeventeen] = useState(false);
    const [eighteen, setEighteen] = useState(false);
    const [nineteen, setNineteen] = useState(false);
    const [twenty, setTwenty] = useState(false);
    const [twentyOne, setTwentyOne] = useState(false);
    const [twentyTwo, setTwentyTwo] = useState(false);
    return (
        <div className='main-container'>
            <div className='w-full mx-auto flex flex-col justify-center items-center pt-4'>
                <div className='w-full mx-auto flex items-center justify-center'><span className='font-bold text-[26px]'>Massage</span></div>
                <div className='w-[100vw] flex items-center justify-center bg-gradient-to-b from-[#02227E] to-[#0247FF] mt-4'><span className='font-bold text-[24px] text-white'>Set Up</span></div>
                <div className='w-full mx-auto flex items-center justify-center mt-2'><span className='font-extrabold text-[24px] text-[#02227E]'>Massage</span></div>
                <div className='grid grid-cols-2 gap-4 mt-2'>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${first == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFirst(!first)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Deep Tissue</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${second == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSecond(!second)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Swedish</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${third == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThird(!third)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Thai</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fourth == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFourth(!fourth)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Shiatsu</span></div></div>
                </div>
                <div className='w-full mx-auto flex items-center justify-center mt-2'><span className='font-extrabold text-[24px] text-[#02227E]'>Sensual Massage</span></div>
                <div className='grid grid-cols-2 gap-4 mt-2'>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fifth == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFifth(!fifth)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Body Rub</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${six == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSix(!six)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Tantra</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${seven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSeven(!seven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Dark tantra</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eight == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEight(!eight)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Prostate</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${nine == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setNine(!nine)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Erotic</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${ten == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTen(!ten)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Nuru</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eleven == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEleven(!eleven)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Foam</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twelve == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwelve(!twelve)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Esalen</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${thirteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setThirteen(!thirteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Lingam</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fourteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFourteen(!fourteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Yoni</span></div></div>
                </div>
                <div className='w-full mx-auto flex items-center justify-center mt-2'><span className='font-extrabold text-[24px] text-[#02227E]'>Release</span></div>
                <div className='grid grid-cols-2 gap-4 mt-2'>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${fifteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setFifteen(!fifteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Therapeutic</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${sixteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSixteen(!sixteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Hand Job</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${seventeen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setSeventeen(!seventeen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Full Service</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${eighteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setEighteen(!eighteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>BBBJ</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${nineteen == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setNineteen(!nineteen)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Prostate</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twenty == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwenty(!twenty)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>CBJ</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyOne == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyOne(!twentyOne)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Grinding</span></div></div>
                    <div className='bg-gradient-to-b from-[#02227E] to-[#0247FF] rounded-[20px] flex flex-row items-center justify-center px-6 pl-8 py-2 h-[38px] relative'><div className='flex items-center justify-center absolute left-1'><button className={`w-[20px] h-[20px] rounded-[100%] border-2 border-[#0CA36C] ${twentyTwo == true ? 'bg-[#08FA5A]' : 'bg-[#D9D9D9]'}`} onClick={() => setTwentyTwo(!twentyTwo)}></button></div><div className='flex items-center justify-center w-[100px] leading-4'><span className='font-bold text-[14px] text-white'>Toys</span></div></div>
                </div>
                <div className='w-full mx-auto flex flex-row justify-between items-center mt-6'>
                    <div className='w-[160px]'><Button className={'flex items-center justify-center border-2 border-[#02227E] rounded-[15px] bg-[#05B7FD] font-bold text-[16px] text-[#02227E]'} text="Massage Services Setup>>" /></div>
                    <div className='w-[160px]'><Button className={'flex items-center justify-center border-2 border-[#02227E] rounded-[15px] bg-[#05B7FD] font-bold text-[16px] text-[#02227E]'} text="Erotic Dance Setup>>" /></div>
                </div>
                <div className='w-full mx-auto flex items-center justify-center mt-6'>
                    <div className='w-[97px]'><Button text="Next>>" className={'flex items-center justify-center border-2 border-[#02227E] rounded-[10px] bg-[#05B7FD] font-bold text-[18px] text-[#02227E] h-[36px]'} size="36px" /></div>
                </div>
            </div>
        </div>
    );
}